export const WEB_SOCKET_CONNECTION_TIMEOUT_MS = 10000

export const WEB_SOCKET_RECONNECT_DELAY_MS = 1000

export const WEB_SOCKET_MAX_RECONNECT_DELAY_MS = 30000

export const WEB_SOCKET_MAX_RECONNECT_ATTEMPTS = 5
